# Generated by Django 3.0.5 on 2022-06-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('Section one', 'Section one'), ('Section two', 'Section two'), ('Section three', 'Section three')], default='one', max_length=50),
        ),
    ]
