# Generated by Django 3.0.5 on 2022-06-05 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20220605_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherextra',
            name='salary',
        ),
    ]
