# Generated by Django 3.0.5 on 2022-06-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_studentextra_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to=''),
        ),
    ]
