# Generated by Django 3.0.5 on 2022-06-05 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_teacherextra_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='teacherextra',
            name='profile_pic',
        ),
    ]
