# Generated by Django 3.0.5 on 2022-06-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20220606_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='RecieverNo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='senderNo',
            field=models.CharField(max_length=15),
        ),
    ]
