# Generated by Django 3.0.5 on 2022-06-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Names',
        ),
    ]
