# Generated by Django 3.0.5 on 2022-06-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_auto_20220610_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='score',
        ),
    ]
