# Generated by Django 3.0.5 on 2022-06-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20220613_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
