# Generated by Django 3.0.5 on 2022-06-19 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_auto_20220619_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='branch',
        ),
    ]
